### ISSUE TITLE
Add the heat content of rain going into the ocean

### ISSUE THREAD

**Issue by jkrasting** [NOAA-GFDL/MOM6#118]
Add the heat content of rain going into the ocean.  Snow assumed to go in at zero degrees.

**Comment by Hallberg-NOAA** [comment]
As a policy, MOM6 issues should deal with the MOM6 code or documentation that are within the MOM6 gitHub repository. Any issues with the diag_tables of specific experiments should be issues for the git repositories for those experiments.

Because the requested diagnostic exists within the MOM6 code, this MOM6 issue has been resolved. @jkrasting, if you still feel that this issue is pertinent to one of the MOM6 configurations, please create a new issue within the git repository for that experiment.
