### ISSUE TITLE
Temperature, salinity and tracer concentration diagnostics are posted before diabatic forcing is applied

### ISSUE THREAD

**Issue by Hallberg-NOAA** [NOAA-GFDL/MOM6#1206]
The diagnostics of the 3-dimensional tracer states, including temperature and salinity, are being posted _before_ any boundary forcing or vertical mixing have been applied. This means that there is an O(dt) error in all of these 3-d tracer state diagnostics, and an inconsistency between fields like that sea surface temperature or surface salinity that are calculated at the correct point in the algorithm and the 3-d temperature and salinity diagnostics.

  In a carefully executed and thoughtful exercise, https://github.com/NOAA-GFDL/MOM6/pull/718 rearranged the MOM6 code to change the point in the algorithm when a number of diagnostics were posted to create remapped tracer transport budgets that close in non-native coordinates. While this exercise did achieve its objectives, in moving the diagnostics from the 3-d tracer concentrations (including temperature and salinity) from post_tracer_diagnostics to post_tracer_transport_diagnostics, it also moved these diagnostics to an earlier point in the algorithm before `diabatic()` has been called unless DIABATIC_FIRST = True (which is not the default value). There is therefore an O(dt) error that was introduced for the 3-d diagnostics of temperature and salinity.

  Thankfully this issue does not impact any of the generic tracers, such as those in biogeochemical packages like bling, TOPAZ or COBALT, because they set `registry_diags=False` in their `register_tracer()` calls, and are therefore responsible for all their own diagnostics.

  The more extensive automated regression testing of diagnostics that has been implemented for MOM6 via Travis since https://github.com/NOAA-GFDL/MOM6/pull/718 would have highlighted the changes, and I think it likely that these issues would have been addressed before the PR was accepted.

 A figure illustrating the severity of this issue by comparing the SST diagnostic with the surface value of the 3-d temperature diagnostic in images taken 6 hours apart in a variant OM4 is attached below, courtesy of Xu Li from NOAA/EMC, is included below.

![image](https://user-images.githubusercontent.com/6529173/92910226-d8ea6b00-f3f5-11ea-9e2b-3a302552a380.png)

**Comment by ashao** [comment]
I agree that my previous PR was the cause of this. However, while this does result in SST and 3D-temperature not being consistent, it's still a valid 'diagnostic' it's just that within a timestep temperature is being posted at a different time. The larger problem in my view is that T, S are not consistent with the other tracers when we have taken great care within the code NOT to distinguish them from other tracers.

For clarity for others seeing this issue, I want to sketchout what the problem by looking at two full steps of the MOM6. One crucial thing (in comparison to other GCMs) to point out is that every process updates the prognostic tracer array, so that at any point within the algorithm, when we post diagnostics it's the current s Essentially, there are two main sub-portions of the model 

(This is valid for `DIABATIC_FIRST = False`)
Timestep 0:
- Timestep 0a. Advection, diffusion, regrid/remap
  - i. Post temperature diagnostics
- Timestep 0b. 'Diabatic' (boundary fluxes and vertical mixing)
- Timsestep 0c. End of timestep
  - i. Posting of surface diagnostics and other tracers
Timestep 1:
- Timestep 1a. Advection, diffusion, regrid/remap
  - i. Post temperature diagnostics
- Timestep 1b. 'Diabatic' (boundary fluxes and vertical mixing)
- Timsestep 1c. End of timestep
  - i. Posting of surface diagnostics and other tracers

The current bug that @Hallberg-NOAA has identified is this:
- Temperature posted at Timestep 1a has had modifications to its state by Timesteps 0b, 0c and 1a. 
- SST at Timestep 1c., is the result of Timesteps 1a, 1b, and 1c.

I *believe* with the way that we define the `enable_averaging` `disable_averaging` the `delta_t` associated with each diagnostic is still 'correct'.

**Comment by Hallberg-NOAA** [comment]
This issue was addressed by MOM6 PR #1207, and can now be closed.
