### ISSUE TITLE
Model Run with and without Islands

### ISSUE THREAD

**Issue by shivsaidixit** [NOAA-GFDL/MOM6#1330]
I am a new user of the model, and want to run two simulations with and without certain islands, and compare the results. What would be best strategy to do this? Can someone guide on this aspect?

**Comment by marshallward** [comment]
Hi @shivsaidixit would you mind re-posting your issue to the MOM6 forums?

https://bb.cgd.ucar.edu/cesm/forums/mom6.148/

It doesn't get a lot of activity at the moment, but we would like for the forum to be the place to handle general support questions.

Support questions can get lost or inadvertently when submitted as issues, since it's generally reserved for model development.  But we will try to leave this open until you start to get a response on the forums.

**Comment by shivsaidixit** [comment]
Thanks for the suggestion. Posted the question on MOM6 forum. https://bb.cgd.ucar.edu/cesm/threads/model-run-with-and-without-islands.5915/

**Comment by marshallward** [comment]
Great, and it looks like you've gotten some interest, so I'll close this.
