### ISSUE TITLE
Make sure all CMOR diagnostics are in the OM4 diag_table

### ISSUE THREAD

**Issue by jkrasting** [NOAA-GFDL/MOM6#136]

**Comment by StephenGriffies** [comment]
diag_table.MOM6 and diag_table.MOM6_CMIP6 
in MOM6-examples/ice_ocean_SIS2/OM4_025 
have been updated with the tag 

221f0b4b57da0d56faa0395da991075d636ca111

This is an incomplete update for the table, as there remain further diagnostics to code.  But we should start to make use of diag_table.MOM6 for development, in order to refine the table further, as well as to refine the analysis scripts.  

More later as diagnostic code is written and as bugs are found in the table...

**Comment by jkrasting** [comment]
If they're not, it's too late!  That ship has sailed ...
