### ISSUE TITLE
ESM4.2 does not restart: Checksum of input field sym_u_ice_C does not match value stored in ice_model.res.nc

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/MOM6#1418]
I am trying FMS1 path in MOM6 dev/gfdl on 06/03/2021 (commit ea0b2bd) + FMS2020.04. 
ESM4.2 (c96+om4p5) crashes upon a restart:
 FATAL from PE     0: SIS_restart(restore_state): Checksum of input field sym_u_ice_C 23E26929448BBBE9 does not match value D26F070EDE705F15 stored in INPUT/ice_model.res.nc

This does not seem to depend on the ocean mask_table or layout , I tried 3 different setups:

/lustre/f2/scratch/Niki.Zadeh/FMSFV2020.04_mom6_20210603_ESM4.2_lndUps_2/ESM4.2_piControl_proto3.1/ncrc4.intel18-prod-openmp/stdout/run/ESM4.2_piControl_proto3.1_2x0m15d_1728x4a_2044x1o.o268826240 

/lustre/f2/scratch/Niki.Zadeh/FMSFV2020.04_mom6_20210603_ESM4.2_lndUps_2/ESM4.2_piControl_proto3.1/ncrc4.intel18-prod-openmp/stdout/run/ESM4.2_piControl_proto3.1_2x0m15d_1728x4a_2592x1o.o268826242 

/lustre/f2/scratch/Niki.Zadeh/FMSFV2020.04_mom6_20210603_ESM4.2_lndUps_3/ESM4.2_piControl_proto3.1/ncrc4.intel18-prod-openmp/stdout/run/ESM4.2_piControl_proto3.1_2x0m15d_1728x4a_1608x1o.o268826302

This same setup works with dev/gfdl on or before 04/28/2021 + FMS2020.04:

/lustre/f2/scratch/Niki.Zadeh/FMSFV2020.04_mom6_20210428_ESM4.2_lndUps_1/ESM4.2_piControl_proto3.1/ncrc4.intel18-prod-openmp/stdout/run/ESM4.2_piControl_proto3.1_2x0m15d_1728x4a_2044x1o.o268808914

I'll try to reproduce this in OM4p5 but have no high hopes for it.

**Comment by Hallberg-NOAA** [comment]
Thank you for this detailed report, @nikizadehgfdl.  I have several other questions that might help us track this down or clarify the situation.

  1. What commit of SIS2 did you use in each case?
  2. If you use the same version of SIS2 but change versions of MOM6, does that trigger the problem?
  3. If you compile with config_src/infra/FMS2 instead of config_src/infra/FMS1, do the restart checksums work?
  4. In all cases if the model is run with RESTART_CHECKSUMS_REQUIRED in one of the SIS_input or SIS_override files, does the model actually reproduce.  (In other words, is this a restart problem or a checksum problem?)
  5. Because the sea-ice state varies greatly, and this may be state dependent, how far into the run do these issues arise?

**Comment by nikizadehgfdl** [comment]
I reproduced this in OM4p5 . It happens for the ice layout of "216,8". Goes away for more balanced layouts of "48,36" or "96,18".  
I'll change xmls to use more sensible ice layouts as such.
Closing.

**Comment by nikizadehgfdl** [comment]
Note: In OM4p5_JRA ice_layouts 
"96,18" and  "100,18" work but 
"192,9" and "180,10" fail to restart.
