### ISSUE TITLE
Format for surface forcing in ocean-only mode using "file"?

### ISSUE THREAD

**Issue by pittwolfe** [NOAA-GFDL/MOM6#1445]
I'm trying to run a simple test case with custom, but time-independent wind stress forcing. The MESO example has such wind stress in MESO_str_025.nc, but the wind stress there is specified on a grid that has one fewer q-point than the grid in ocean.geometry or in the forcing diagnostic output. I'm fine with leaving off a q-point, but is it the first or last q-point? 

Also, the metadata in the MESO_str_025.nc says that the stress is in dyne/cm^2, which is a factor of 10 different from a Pa ... what units does the model expect wind stress to have?

**Comment by Hallberg-NOAA** [comment]
Thanks for this inquiry, @pittwolfe. There are two separate issues here:

  1. The wind stress input files for MESO are missing the southernmost row of v-points, and the westernmost row of points of u-points.  In a case like MESO that is zonally reentrant, a series of halo updates (calls to fill_symmetric_edges() and pass_vector()) fills in the extra u-point stress with the proper value, and there is no problem.  The southernmost v-point stresses are on land or coastlines, so they are _mostly_ not used.  I say _mostly_ because the stresses on coastlines do not contribute to accelerations, but the magnitudes of the stresses at the velocity points might be interpolated to the tracer points when calculating the friction velocity (u*), which in turn may be used in some mixing or boundary layer parameterizations.  (There is also the option in MOM6 to read in the friction velocity directly from a file by providing its name in the input file with USTAR_FORCING_VAR.)  The omission of the southernmost row of v-point stresses means that the friction velocity might be underestimated in the southernmost row of tracer points.  For this reason, it is always better to provide the full symmetric-array stresses in an input file.  (None of this discussion has any bearing on coupled models, for which all the stresses are provided by the coupler, often at the tracer points, and there need not be any interpolation in determining the friction velocities.)
  
    The MESO wind stress input file is a hold-over from a very old (~2003) set of published runs that used a different model  (HIM) written in a different language (C), but that we are able to reproduce nonetheless in MOM6.  Curiously, MESO is the one configuration in MOM6-examples that is unable to run with symmetric memory allocation. In the interests of making this a better example, it would probably be a good idea to provide an updated set of input files with the extra southern row of v-point stresses, precisely to avoid the confusions that are noted in inquiry, but we have not gotten around to doing so.

  2. MOM6 generally expects input to be in MKS units, be we can not always control what is in the files we are given, so MOM6 allows for the wind stresses to be rescaled when they are read. In the case of MESO, where the wind stresses were in dyne/cm^2 in the original input dataset, this is accomplished by setting the runtime parameter `WINDSTRESS_SCALE = 0.1` in the MOM_input or MOM_override file.  If this wind stresses in the file were in the proper MKS units of Pa, the model would use the default value of `WINDSTRESS_SCALE = 1.0` This rescaling for differing units is not done automatically based on the input file metadata, so there is some reliance on the user to verify that they are getting what they intended. 

  In response to both issues, one thing that a user can always do is to have the model write out the wind stresses that it actually uses to a diagnostic file, to verify that they have the units and patterns that are expected.

**Comment by pittwolfe** [comment]
Thanks!
