### ISSUE TITLE
Request calendar date progress messages

### ISSUE THREAD

**Issue by amylangenhorst** [NOAA-GFDL/MOM6#200]
For models running with a calendar, it would be helpful to see the calendar date in stdout to monitor run progress, rather than (or in addition to) the absolute date:

MOM Day  711765.000 

Affects SIS as well:

SIS Day  711765.250

**Comment by adcroft** [comment]
Good suggestion. Those unintelligible big numbers have bugged me for over 61324 hours. :)

We use that string ("MOM Day %f") in both the stdout and the ascii timestats file. I'm assuming you are only concerned with the stdout stream?

I'm going ahead and updating the format for stdout so that
> MOM Day  693135.250      6: En 7.313960E-04, MaxCFL  0.13640, Mass 1.381839985229E+21, Salt  34.72021005222, Temp   3.60425739582

becomes
> MOM Date   1900/01/01 06:00:00      6: En 7.313960E-04, MaxCFL  0.13640, Mass 1.381839985229E+21, Salt  34.72021005222, Temp   3.60425739582

allowing for up to 10^6 in the year entry.

Changing the timestats file format requires more thought since we use those files for regression testing (and there are too many balls in the air to risk updating all those regression files right now). I'm also going to think about how to detect whether the user means to use a calendar or not...

**Comment by amylangenhorst** [comment]
Thanks, Alistair!  Yes, I was just interested in the stdout file at this point.

**Comment by adcroft** [comment]
@amylangenhorst  This is implemented in both MOM6 and SIS2 and available on dev/master branch but won't be in an XML until the next tag on dev/master.
