### ISSUE TITLE
Unnecessary pass_var in Radiation_Open_Bdry_Conds

### ISSUE THREAD

**Issue by nichannah** [NOAA-GFDL/MOM6#204]
subroutine Radiation_Open_Bdry_Conds()

takes h variables as dummy arguments. These are not used (commented out), also pass_var() on this variable may be called unnecessarily.

**Comment by Hallberg-NOAA** [comment]
This issue has long-since been addressed. The unused argument h to Radiation_Open_Bdry_Conds() was removed on April 10, 2017, with commit https://github.com/NOAA-GFDL/MOM6/commit/08b37e97e3df146f5685aeb82e3727d9e354a775, while the unnecessary halo update was removed as a part of PR#417 on Feb. 13, 2017.
