### ISSUE TITLE
Buffer overflow logging ALE_RESOLUTION

### ISSUE THREAD

**Issue by angus-g** [NOAA-GFDL/MOM6#214]
With enough vertical levels (I'm using `NK = 72`), it's possible for there to be a buffer overflow in the string creation routines involved in logging `ALE_RESOLUTION`, with an error somewhat like

`forrtl: severe (66): output statement overflows record, unit -5, file Internal Formatted Write`

I've temporarily fixed this locally by bumping up some buffers from 1320 to 2000 characters, but this seems like a bit of a hacky solution. It'd probably be better to check that writes to strings won't overflow, instead.

**Comment by hmkhatri** [comment]
I am trying to set up a continuously stratified channel model with 75 vertical levels (ALE z* coordinate). The code returns the same error,

forrtl: severe (66): output statement overflows record, unit -5, file Internal Formatted Write

**Comment by Hallberg-NOAA** [comment]
This issue was addressed by using a deferred length for a number of character strings, which was added via (https://github.com/NCAR/MOM6/pull/165), which in turn was added to the main branch by PR #1275.  If a similar issue is encountered again, even more use should be made of deferred length strings.
