### ISSUE TITLE
Out of bounds index (por_face_areaU) related to #3

### ISSUE THREAD

**Issue by wfcooke** [NOAA-GFDL/MOM6#24]
In testing some updates I got an out of bounds index for 
https://github.com/NOAA-GFDL/MOM6/blob/6494852872b809352e417bd2adf3f6a567004e76/src/core/MOM_continuity_PPM.F90#L522

Subscript #3 of the array POR_FAC_AREAU has value .....

I'm not seeing a loop for subscript 2 (J) either.

I guess there isn't a test with set_BT_cont=True

line 519 has the same issue.

Will

**Comment by marshallward** [comment]
I agree with @wfcooke that `i` and `j` are unset here, and don't match the function definition anyway.

`por_face_areau` does not even appear to be used in `zonal_face_thickness`.  Maybe it can be removed? (ping @sditkovsky)

Same applies to `merid_face_thickness`, which is passing full arrays (hence no error) but is also unused in the function.

**Comment by Hallberg-NOAA** [comment]
These `por_face_area` arguments describe fractional horizontal extents, but `zonal_face_thickness()` and `merid_face_thickness()` deal only with vertical extents. It is hard to imagine that these `por_face_area` arguments would every be used in these routines, and I think that they can be safely removed.

**Comment by sditkovsky** [comment]
Yes, sorry about this. These arguments can be safely removed. They must be left over from an earlier version of the modifications where I was also modifying the CFL values with the porous factor, but the final version did not include those changes.

**Comment by Hallberg-NOAA** [comment]
Upon further reflection, I think that we actually want to include the faces' fractional open widths in these face thickness estimates. The only use of these thicknesses is as relative weights for the various layers' accelerations in estimating the barotropic accelerations (via the fractional weights `frhat[uv]` that are set in `btcalc()`. When `visc_rem_[uv]` these relative thicknesses are already being modified by a scaling factor in the range of (0,1] to account for the effects of vertical viscosity.  I think that we want to the same with `por_face_area[UV]`, but also modify the comments describing the `h_u` and `h_v` arguments to `btcalc()` and the description of the `h_u` and `h_v` elements of the BT_cont_type.

  Based on this more careful consideration, the right solution for this specific issue with out-of-bounds arrays is not to eliminate these two arguments, but rather to change the calls from `call zonal_face_thickness(..., por_face_areaU(:,j,k), visc_rem_u)` to  `call zonal_face_thickness(..., por_face_areaU, visc_rem_u)`.

  For further development of this new porous boundary capability, it might be worth noting that wherever and whenever the visc_rem variables are used in MOM, they probably should be (and mostly are) multiplied by a por_face_area variable, although this would change answers when the porous boundares are enabled.  @sditkovsky, since you are probably the only person using this yet, please coordinate with me to figure out how we want to handle this additional change.
