### ISSUE TITLE
dynamic_symmetric running, but tiles show

### ISSUE THREAD

**Issue by kshedstrom** [NOAA-GFDL/MOM6#282]
This is our CCS1 domain on 32 cores after eight days:
SSU
![ssu](https://cloud.githubusercontent.com/assets/444446/15025592/6fc36028-11e6-11e6-8994-8847c25a975c.png)
SSV
![ssv](https://cloud.githubusercontent.com/assets/444446/15025594/717ce2ae-11e6-11e6-930a-17ce4688e5da.png)

**Comment by kshedstrom** [comment]
Running dueling debuggers, with and without symmetric (4 cores each):
I don't know how it happens, but the jec+1 values of T_t and friends end up different out of pressure_gradient_plm, for instance 18.951957 vs 18.951646. This leads to the jec values of PFv being different later.

**Comment by kshedstrom** [comment]
The tracers at jec+1 differ after the call to do_group_pass at line 697 of MOM.F90.

**Comment by kshedstrom** [comment]
Somehow the ML_depth gets off in the non-southern tiles at jec in MOM_energetic_PBL, can't say how. I suspect tauy, which is zero at jec-1 for dynamic_symmetric, non-zero for dynamic.
![sym](https://cloud.githubusercontent.com/assets/444446/15058794/db35ef6c-12ca-11e6-9d75-b4036cf0b2e3.png)
![dyn](https://cloud.githubusercontent.com/assets/444446/15058798/dc5a3a2e-12ca-11e6-9f86-b87905c7f46c.png)
I'd change tauy and try again if I knew what to change.

**Comment by adcroft** [comment]
Is this the exact configuration given by [CCS1/MOM_parameter_doc.all](https://github.com/ESMG/ESMG-configs/blob/dev/master/CCS1/MOM_parameter_doc.all) or do you have local updates?

**Comment by kshedstrom** [comment]
It's this configuration:
https://github.com/ESMG/ESMG-configs/blob/user/ksh/open_bc/CCS1/MOM_parameter_doc.all

I don't think it's different in any meaningful way.

**Comment by Hallberg-NOAA** [comment]
There is obviously an issue with missing halo updates in this configuration.

  Within the MOM6 code, there is another approach to track down problems like this.  If you set the run-time flag DEBUG=True, MOM6 will write out a series of checksums  to std_err as the model progress, along with informative messages about which fields are being checked.  This output is independent of processor count, provided the solutions themselves are the same. So to debug a parallelization issue (like this one), we do two short runs with different PE counts (say, 32 and 31), and look for the first point in the code where the output starts to differ.  We then grep through the code to see where the first differing call can be found, providing a very good indication of where in the code the parallelization issue occurs.

  This tends to generate a lot of output to std_err, so very short runs are advised.  Also, unless you think that the problem is in the barotropic solver, it is a very good idea to set DEBUG_BT=False to reduce the number of messages.

**Comment by StephenGriffies** [comment]
Hi,

I found this email quite useful.  I thus placed a slightly edited version
on the MOM6 Wiki at the bottom of

https://github.com/NOAA-GFDL/MOM6-examples/wiki/Developers-guide

I suggest we continue to place such "gems" of information on the Wiki.

Steve






On Fri, May 6, 2016 at 1:12 PM, Robert Hallberg <notifications@github.com>
wrote:

> There is obviously an issue with missing halo updates in this
> configuration.
>
> Within the MOM6 code, there is another approach to track down problems
> like this. If you set the run-time flag DEBUG=True, MOM6 will write out a
> series of checksums to std_err as the model progress, along with
> informative messages about which fields are being checked. This output is
> independent of processor count, provided the solutions themselves are the
> same. So to debug a parallelization issue (like this one), we do two short
> runs with different PE counts (say, 32 and 31), and look for the first
> point in the code where the output starts to differ. We then grep through
> the code to see where the first differing call can be found, providing a
> very good indication of where in the code the parallelization issue occurs.
>
> This tends to generate a lot of output to std_err, so very short runs are
> advised. Also, unless you think that the problem is in the barotropic
> solver, it is a very good idea to set DEBUG_BT=False to reduce the number
> of messages.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/NOAA-GFDL/MOM6/issues/282#issuecomment-217501949>
>



-- 
Dr. Stephen M. Griffies
NOAA Geophysical Fluid Dynamics Lab
201 Forrestal Road
Princeton, NJ 08542
USA

**Comment by kshedstrom** [comment]
Thanks Bob and Steve. For this case with 31 vs 32 processes, the first
diffs are here:

287,288c278,279
<              MOM_initialize_fixed: Rlay     2.4051770670000E+06
61349
<           MOM_initialize_fixed: g_prime     3.1215963671498E+02
77903
---
>              MOM_initialize_fixed: Rlay     2.4827634240000E+06
63328
>           MOM_initialize_fixed: g_prime     3.2222930241546E+02
80416

Kate

**Comment by Hallberg-NOAA** [comment]
Ok, my bad (partly).  I fixed this particular problem this morning, where 1-d arrays (Rlay and g_prime) that are the same on all processors were being summed across processors, not compared.  In fact I waited with my previous message until I had everything working as intended with the DEBUG option and different processor counts.  If you were to update your code to NOAA-GFDL/MOM6@5f37211cb9ca06d0a3e4d62fe5608f66e7bb2537 or later, you will find that the first difference really is where the two solutions diverged.  You will know you have found the divergence point also because after the two solutions start diverging, they do not come back together. Sorry about the confusion!

**Comment by kshedstrom** [comment]
Hi Bob,

I did figure out that's what was going on, but didn't think to fetch
updates again.

Here's the first divergence:

351,353c361,363
<  ATM(ATMOCNLND)=   8.2117285119921533E-003   8.2117285119921533E-003
8.21172
85119921515E-003
<  OCN(ATMOCNLND)=   6.7631664087959764E-003   6.7631664087959764E-003
6.76316
64087959764E-003
<  LND(ATMOCNLND)=   1.4485621031961765E-003   1.4485621031961765E-003
1.44856
21031961765E-003
---
>  ATM(ATMOCNLND)=   8.2117285119921585E-003   8.2117285119921550E-003
8.21172
85119921585E-003
>  OCN(ATMOCNLND)=   6.7631664087959807E-003   6.7631664087959798E-003
6.76316
64087959798E-003
>  LND(ATMOCNLND)=   1.4485621031961760E-003   1.4485621031961756E-003
1.44856
21031961756E-003

Plus more of the same ilk, followed by:

364,365c374,375
< CHECKSUM::     atm%lon_bnd                 =     B1032F26F51FBEBE
< CHECKSUM::     atm%lat_bnd                 =     70BCB322A359765E
---
> CHECKSUM::     atm%lon_bnd                 =     FFD20B7DBFA4DBB0
> CHECKSUM::     atm%lat_bnd                 =     31DE82607067012B

Kate

**Comment by Hallberg-NOAA** [comment]
Alas, but this is another red herring, this time coming from the FMS coupler, which does not use the MOM6-style bitwise reproducing sums, and can change slightly with differing layouts. Sorry about that! (This does not occur with the ocean-only cases.)  These are not the lines that will help us in debugging the issue.  The lines that are written with DEBUG=True  that you want to examine for differences will look like the following:

u-point: c=    428544 sw=    321408 se=    317733 nw=    321408 ne=    317733 Before steps  u

This example is from variable "u" taken at the "Before steps" point in the code. "u" is discretized at a "u-point", and the 5 numbers are the checksums (sums of the bits in each variable) based on the values in the computational domain, and the values when that domain is shifted to the southwest, southeast, northwest, and northeast to check the values in the halo regions.  (Some fields that do not have up-to-date halos omit the latter 4 numbers.)

**Comment by kshedstrom** [comment]
OK, fine. We're back to taux, tauy:

554,556c564,566
< u-point: c=   2363060 sw=   2341474 se=   2341483 nw=   2341201 ne=
2341212
Before steps fluxes%taux
< v-point: c=   2359975 sw=   2286581 se=   2271721 nw=   2353559 ne=
2338275
Before steps fluxes%tauy
< h-point: c=   2810905 Before steps fluxes%ustar
---
> u-point: c=   2363060 sw=   2357350 se=   2341483 nw=   2357076 ne=
2341212
Before steps fluxes%taux
> v-point: c=   2359975 sw=   2212617 se=   2198239 nw=   2353559 ne=
2338275
Before steps fluxes%tauy
> h-point: c=   2811616 Before steps fluxes%ustar

Thanks!
Kate

**Comment by Hallberg-NOAA** [comment]
I think that we might have a nonblocking halo update for the wind stresses and surface pressure that needs to be turned into a blocking update.  Please try commenting out lines 554-556, 558, and 597-601 of MOM.F90 and see whether this helps or even changes the solutions - either case would indicate that this update is an issue where we got overly greedy with optimizing the speed of our paralleization. (These are all lines that relate to CS%pass_tau_ustar_psurf, in case the line numbers are different in your version of MOM.F90.)

**Comment by kshedstrom** [comment]
Yes, I commented out those lines and the two day solution looks much
better. Still, I now get:

787c787
< h-point: c= 198958732 sw= 199058907 se= 199374860 nw= 199048629 ne=
199364633
after applyBoundaryFluxes  h
---
> h-point: c= 198958732 sw= 199067963 se= 199384236 nw= 199059188 ne=
199375408
after applyBoundaryFluxes  h
790c790
< h-point: c= 198958732 sw= 199058907 se= 199374860 nw= 199048629 ne=
199364633
after negative check  h
---
> h-point: c= 198958732 sw= 199067963 se= 199384236 nw= 199059188 ne=
199375408
after negative check  h

Cheers,
Kate

**Comment by kshedstrom** [comment]
Oops, no, that wasn't it. I switched computers and forgot to go to
dynamic_symmetric mode. It was simply dynamic mode that had the differences
in the last message. Dynamic_symmetric still has the taux, tauy errors.

I got suspicious because one computer had a lot more output than the other,
pages and pages of this stuff:

<         Predictor 1 up Layer 1 redundant v-comps  4.0799E-04  4.1032E-04
differ by  -2.3292E-06 at i,j =   13   4 x,y =   2.3880E+02  2.0535E+01 on
pe    2
<         Predictor 1 up Layer 1 redundant v-comps  4.3531E-04  4.3765E-04
differ by  -2.3353E-06 at i,j =   14   4 x,y =   2.3886E+02  2.0563E+01 on
pe    2
<         Predictor 1 up Layer 1 redundant v-comps  4.5018E-04  4.5252E-04
differ by  -2.3405E-06 at i,j =   15   4 x,y =   2.3892E+02  2.0592E+01 on
pe    2
<         Predictor 1 up Layer 1 redundant v-comps  4.6477E-04  4.6711E-04
differ by  -2.3452E-06 at i,j =   16   4 x,y =   2.3898E+02  2.0620E+01 on
pe    2

Kate

**Comment by Hallberg-NOAA** [comment]
This is the second type of test that we use for parallelization, which only works for a tripolar grid or symmetric memory. In these cases, the same field and location are calculated twice on different processors, and the model checks that these redundant values are identical.  With this test, we can detect parallelization or symmetry errors using only a single run.

  This particular message is coming from line 591 of MOM.F90. For the historical reason that we have never encountered a problem here before, we don't have corresponding calls to check_redundant for the 3 terms that contributed to vp in the loops at lines 571-572. Adding similar calls to check_redundant for the (u_init,v_init), (u_bc_accel,v_bc_accel) and (CS%u_bt_accel, CS%v_bt_accel) couplings would be the next step in tracking this problem back to its source. (At that point you could also use a debugger to set a break-point on the line that is issuing this message in check_redundant_v3d and then backtrack from there.) If the problem turns out to be coming out of btstep, you would need to turn on DEBUG_BT as well as DEBUG, but be advised that this _greatly_ increases the volume of output to std_err, so make sure you do this with a short run!

  At this point, Kate, if I had access to your set-up, I could help you debug this specific case, but I am writing this detailed response in part because I have gotten the feedback that this dialog on how to debug MOM6 parallelization is actually useful for others as we look ahead to introducing and debugging other similar issues.

**Comment by StephenGriffies** [comment]
Kate,

As you further refine your understanding of debugging, please place these
nuggets of information on the MOM6 Wiki.

Thanks,
 Steve



On Mon, May 9, 2016 at 6:08 AM, Robert Hallberg <notifications@github.com>
wrote:

> This is the second type of test that we use for parallelization, which
> only works for a tripolar grid or symmetric memory. In these cases, the
> same field and location are calculated twice on different processors, and
> the model checks that these redundant values are identical. With this test,
> we can detect parallelization or symmetry errors using only a single run.
>
> This particular message is coming from line 591 of MOM.F90. For the
> historical reason that we have never encountered a problem here before, we
> don't have corresponding calls to check_redundant for the 3 terms that
> contributed to vp in the loops at lines 571-572. Adding similar calls to
> check_redundant for the (u_init,v_init), (u_bc_accel,v_bc_accel) and
> (CS%u_bt_accel, CS%v_bt_accel) couplings would be the next step in tracking
> this problem back to its source. (At that point you could also use a
> debugger to set a break-point on the line that is issuing this message in
> check_redundant_v3d and then backtrack from there.) If the problem turns
> out to be coming out of btstep, you would need to turn on DEBUG_BT as well
> as DEBUG, but be advised that this *greatly* increases the volume of
> output to std_err, so make sure you do this with a short run!
>
> At this point, Kate, if I had access to your set-up, I could help you
> debug this specific case, but I am writing this detailed response in part
> because I have gotten the feedback that this dialog on how to debug MOM6
> parallelization is actually useful for others as we look ahead to
> introducing and debugging other similar issues.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/NOAA-GFDL/MOM6/issues/282#issuecomment-217859205>
>



-- 
Dr. Stephen M. Griffies
NOAA Geophysical Fluid Dynamics Lab
201 Forrestal Road
Princeton, NJ 08542
USA

**Comment by Hallberg-NOAA** [comment]
There was a missing call to fill_symmetric_edges for the wind stresses in the case of the ocean running in symmetric memory mode.  This call is necessitated because the FMS coupler only works on the exchange of non-symmetric arrays. New code that was introduced in NOAA-GFDL@17ec5f5ef8648a3bcc974f5dba1ace38519f2454 corrects this problem.

  I hope that everyone reading this exchange found this issue to be an illuminating tour of our approach to debugging and assuring certain types of self-consistency in MOM6!

**Comment by kshedstrom** [comment]
Thanks, Bob!

I'm left with just this diff in a one-hour run:

942c942
< h-point: c= 196720239 sw= 196851459 se= 197367637 nw= 196862523 ne=
197378745
Predictor 1 init h
---
> h-point: c= 196720239 sw= 196852434 se= 197368612 nw= 196863498 ne=
197379720
Predictor 1 init h
991c991
< h-point: c= 196720239 sw= 196851459 se= 197367637 nw= 196862523 ne=
197378745
Corrector 1 h
---
> h-point: c= 196720239 sw= 196852434 se= 197368612 nw= 196863498 ne=
197379720
Corrector 1 h
1396c1396
< h-point: c= 200162752 sw= 200279675 se= 200746077 nw= 200297905 ne=
200764361
Predictor 1 init h
---
> h-point: c= 200162752 sw= 200280650 se= 200747052 nw= 200298880 ne=
200765336
Predictor 1 init h
1445c1445
< h-point: c= 200162752 sw= 200279675 se= 200746077 nw= 200297905 ne=
200764361
Corrector 1 h
---
> h-point: c= 200162752 sw= 200280650 se= 200747052 nw= 200298880 ne=
200765336
Corrector 1 h

Meaningful or not?

Kate

**Comment by Hallberg-NOAA** [comment]
Looking at the code and these differences, they arise from the halo regions only, and in both cases there are 2-point wide halos being checked (h is checked with a haloshift of 1 just above the "Predictor 1 init" check.  If the differences do not spread (i.e., the computational domains stay the same, and only these lines continue to differ), this is not meaningful.

   I did not get this in the Baltic test case, but that could be because some of the settings earlier on in MOM.F90 led to a halo update on h that caused all of the halo values to be the same.  If your solutions themselves are the same, please let me know and I will fix the halo widths for these debugging diagnostics.

**Comment by kshedstrom** [comment]
The one day solutions are the same.

Thanks,
Kate
