### ISSUE TITLE
Baltic test case doesn't run on a single proc

### ISSUE THREAD

**Issue by nicjhan** [NOAA-GFDL/MOM6#330]
Is this related to changes to FMS mentioned in #298? 

It's nice from a machine setup and testing point-of-view to not have to install and use MPI.

**Comment by adcroft** [comment]
This is not related to #298 because Baltic is 3D (xyz) and has a wide enough domain for 4-point halos.

I was also able to build __without MPI__ by removing the mpich2 section from LIBS in linux-intel.mk (Intel 11.1.073), and not using -Duse_libMPI at the command line. I am using the verona release of FMS and did not check wheth ulm worked.

I double checked that I am able to run Baltic in single-core with all compilers and in production/debug mode using MPI.

@nicjhan Can you elaborate on this issue (or check that verona fixed it)?

**Comment by nicjhan** [comment]
Thanks @adcroft, yes this is no longer a problem. I didn't document the issue well enough to try to reproduce and take a guess at the cause.
