### ISSUE TITLE
ocean-ice tests crash with Intel16 on c4

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/MOM6#383]
dev/master/2016.10.25

I get the following crash when I try to run any ocean-ice experiment on c4 with Intel16 executable (compiled on gaea13).
```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source

fms_MOM6_SIS2_com  000000000077E218  ocean_model_mod_m         728  ocean_model_MOM.F90
fms_MOM6_SIS2_com  000000000077B05D  ocean_model_mod_m         488  ocean_model_MOM.F90
```

The experiments run fine on c3 with Intel15.

I tried one experiment (1/4 degree baseline) on c4 with the c3 executable (Intel15)   and it ran fine!

I'll dig in more, but here's my Intel16 exec if you want to try it on c4 

```
/lustre/f1/unswept/Niki.Zadeh/verona_mom6_2016.10.25/MOM6_SIS2_compile/ncrc4.intel16-prod-openmp/exec/fms_MOM6_SIS2_compile.x
```

**Comment by nikizadehgfdl** [comment]
I think this might be an Intel16 compiler issue because: 

1. The above crash happens only when I compile MOM6 with -openmp -O3 with Intel16 (and use 1 OMP thread).

2. I cannot even compile with -openmp -O2, the compiler panics like:
```
  catastrophic error: **Internal compiler error: segmentation violation signal raised** Please report this error along with the circumstances in which it occurred in a Software Problem Report.  Note: File and line given may not be explicit cause of this error.
compilation aborted for /lustre/f1/unswept/Niki.Zadeh/verona_mom6_2016.10.25/OM4_libs_compile/src/mom6/src/MOM6/src/framework/MOM_checksums.F90 (code 1)
``` 

3. There are no such issues when I compile/run with Intel15 with or without -openmp , or  Intel16 without -openmp.

**Comment by nikizadehgfdl** [comment]
Coming back to this, it is still happening in dev/master/2017.05.26, only the line numbers for traceback have changed.
```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
fms_MOM6_SIS2_com  000000000073C880  ocean_model_mod_m         803  ocean_model_MOM.F90
fms_MOM6_SIS2_com  00000000007381B2  ocean_model_mod_m         507  ocean_model_MOM.F90

```

Looking closer at the offending lines, this is so very strange since line 803 should never even be stepped in because argument patm is not present:

```
  do j=jsc_bnd,jec_bnd ; do i=isc_bnd,iec_bnd
    Ocean_sfc%sea_lev(i,j) = state%sea_lev(i+i0,j+j0)
    if (present(patm)) &
      Ocean_sfc%sea_lev(i,j) = Ocean_sfc%sea_lev(i,j) + patm(i,j) * press_to_z   !----    line 803
      if (associated(state%frazil)) &
      Ocean_sfc%frazil(i,j) = state%frazil(i+i0,j+j0)
    Ocean_sfc%area(i,j)   =  G%areaT(i+i0,j+j0)
  enddo ; enddo
```

Commenting out lines 802 and 803 (which should have no effect)  let's the model run  with Intel16+openmp and preserves ocean.stats with and without OMP threads !!

**Comment by nikizadehgfdl** [comment]
This  OMP issues are resolved as of dev/gfdl/2017.10.05. Closing!

**Comment by hlkong** [comment]
Hi,

Sorry to bother you but I ran into a similar problem when running the ocean_only version of MOM6. Specifically, I got this message repeatedly:

>forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
MOM6               00000000012D9C81  Unknown               Unknown  Unknown
MOM6               00000000012D83D7  Unknown               Unknown  Unknown
libnetcdff.so.6    00007F1782840D62  Unknown               Unknown  Unknown
libnetcdff.so.6    00007F1782840BB6  Unknown               Unknown  Unknown
libnetcdff.so.6    00007F178282760C  Unknown               Unknown  Unknown
libnetcdff.so.6    00007F178282B678  Unknown               Unknown  Unknown
libpthread.so.0    00007F177DA99100  Unknown               Unknown  Unknown
MOM6               00000000009756C3  mom_barotropic_mp        1477  MOM_barotropic.F90
MOM6               0000000000CC4D92  mom_dynamics_spli         495  MOM_dynamics_split_RK2.F90
MOM6               0000000000B29553  mom_mp_step_mom_          860  MOM.F90
MOM6               000000000081F303  MAIN__                    473  MOM_driver.F90
MOM6               0000000000406DBE  Unknown               Unknown  Unknown
libc.so.6          00007F177D3E8B15  Unknown               Unknown  Unknown
MOM6               0000000000406CC9  Unknown               Unknown  Unknown

I'm just wondering if you happen to know how your issue was resolved previously?

Thank you so much!

**Comment by adcroft** [comment]
Hallu,

These look like different issues. Your traceback is coming from the netcdf
library from within the barotropic solver - which itself is odd. This issue
is closed so can create a new issue and in addition to the above also
report the commit you are using (git show) because line 1477 in the latest
code is not likely to be causing your problem.

--
Dr Alistair Adcroft    (Alistair.Adcroft@noaa.gov)
Princeton University           Tel: (609) 987-5073
NOAA/GFDL, 201 Forrestal Road, Princeton, NJ 08540

**Comment by hlkong** [comment]
Thank you so much Alistair! I will open a new issue on this.

Cheers,

Hailu
