### ISSUE TITLE
Rotate simulations and compare to vanilla run

### ISSUE THREAD

**Issue by nichannah** [NOAA-GFDL/MOM6#391]
Develop the capabilities of MOM6 to run and evaluate pairs of simulations that are rotated in orientation to identify and correct inconsistencies in the spatial discretization of MOM6.

For example, if we rotate all model inputs by 180 deg, perform the simulation and then rotate results back this should be equivalent to an unrotated run. We foresee that this will pick up problems with i, j indexing.

**Comment by Hallberg-NOAA** [comment]
For 180-degree rotations we already have some confidence that things will be right based on identical redundant calculations on and around the tripolar fold.  Some of what we will detect with 90-degree rotations will be simply inconsistencies between how the i- and j- directions are coded, and not necessarily errors (e.g., different equally valid choices about where to put parentheses).  However, if the model can be made to exactly reproduce with both 90 and 180 degree rotations, it will essentially rule out the possibilities of undetected horizontal indexing errors.

**Comment by nicjhan** [comment]
Hi @Hallberg-NOAA, I've had some time to experiment with this idea. Please let me know if you have any comments on my approach so far.

- For the time being I'm focusing on square domains using non-symmetric memory so that I don't have to change the extents of i's and j's. Also working on a single proc only. I've been using the double-gyre experiment to begin with.  

- All of my configuration is presently done from within the model, i.e. there is no change made to MOM_memory_macros.h and no need to recompile. A switch controls whether or not inputs will be rotated. 

- I'm rotating grids, ICs, fluxes etc. at a particular place in the initialization, and also rotating the chksums so that I can see when things start to go wrong. 

- Perhaps it goes without saying but there are several cases or types of symmetry in the code: 180 degree, 90 degree and u, v symmetry. 180 degree symmetry happens where i and j ops are symmetrical but can be different to each other. 90 degree is where i and j do the same thing. By u, v, symmetry I mean when there are two similar pieces of code one for u, one for v - this requires 90 deg symmetry.  

- Our task, as you said, is to make these symmetries hold. We can test them by transforming data/inputs to match the code symmetries and expect the results to be identical. 

- As an example of the above, we can check u, v code symmetry by swapping u and v, then rotating by 90. u will now be calculated by the v code and vice-versa however the results will be the same. Equivalently we could do without separate u and v code altogether and have one generic 'velocity' code - this would calculate v then rotate all inputs by 90 degrees and calculate u. The advantage of this would be less code, the disadvantage would be performance cost of rotations. 

- Code may need to be changed to make it symmetrical (?) For example btcalc() which calculates both CS%frhatv and CS%frhatv has loops look like:

for U:

do j=js-1,je+1
      do I=is-2,ie+1

for V:

do J=js-2,je+1
     do i=is-1,ie+1

I don't think this will be 180 deg symmetrical because i goes from i-2 to i+1 so the east and west work is not identical. I don't think it will be 90 deg sym because the i and j ranges are different (js-1 vs is-2). u, v symmetry could be OK.

**Comment by nicjhan** [comment]
An update: 

This is going well, however can be time-consuming. e.g. presently I'm chasing a +1 difference in a bitcount about 1/2 way through a run. Good news is that it's getting easier. 

My expectation of finding bugs is rapidly waning! My approach will find:

1. non-symmetrical treatment of i, j in calculations which should be direction independent. (i.e. not to do with u, v)
2. differences between u and v directed calculations. i.e. I'm calculating u with v code and vice-versa.

The code seems to be standing up perfectly to these checks.

**Comment by marshallward** [comment]
This has now been implemented.
