### ISSUE TITLE
Please add interp_method=none to non-regriddable static diagnostics

### ISSUE THREAD

**Issue by ceblanton** [NOAA-GFDL/MOM6#406]
Non-regriddable time-varying diagnostics have attribute interp_method=none set, so fregrid won't attempt to regrid them. However, many non-regriddable static fields don't have the attribute set, but should. As a result, frepp/fregrid have errors when regridding the tripolar scalars to lat/lon.

Please set these diagnostics to have attribute interp_method=none set:

ocean_geometry: geolatb, geolonb, f, Aq, dxCv, dyCu, dxCu, dyCv, dxBu, dyBu, dxCvo, dyCuo

ocean_static: Coriolis, dxCv, dyCu, dxCu, dyCv, geolat_c, geolon_c, geolat_u, geolon_u, geolat_v, geolon_v, wet_c, wet_u, wet_v

ocean_static_no_mask_table: Coriolis dxCv dyCu dxCu dyCv geolat_c geolon_c geolat_u geolon_u geolat_v geolon_v wet_c wet_u wet_v

**Comment by adcroft** [comment]
We already added `interp_method` to all those variables in 571b397e3a3. See https://github.com/NOAA-GFDL/MOM6/blob/dev/master/src/core/MOM.F90#L3484

Seeing your msg, I did just realized that "f" should __not__ be in that list since it can be interpolated.

I just checked again that the attribute is appearing in the ocean_static.nc files when I run tests:
```
	float dyCu(yh, xq) ;
		dyCu:long_name = "Delta(y) at u points (meter)" ;
		dyCu:units = "m" ;
		dyCu:missing_value = -1.e+34f ;
		dyCu:_FillValue = -1.e+34f ;
		dyCu:cell_methods = "time: point" ;
		dyCu:interp_method = "none" ;
```

I suggest you look to the work flow for why the attribute is missing. The model is definitely writing it out.

I'll leave this open until you confirm I can close it.

**Comment by ceblanton** [comment]
Leaving aside ocean_geometry, interp_method=none was added to all those except:
      geolon_c geolat_c geolon_u geolat_u geolon_v geolat_v
which although theoretically regriddable, fregrid doesn't currently regrid, and so would be best to add to those as well
