### ISSUE TITLE
Transform test fails in tracer_epipycnal_ML_diff()

### ISSUE THREAD

**Issue by nichannah** [NOAA-GFDL/MOM6#518]
There is significant difference between treatment of I and j directions in tracer_epipycnal_ML_diff(), particularly towards the end of the subroutine. The transform test relies on the code being the same in both directions. @adcroft or @Zhi-Liang could you take a look at this, particularly commit d93cacde and see whether it can be made the same for both u and v?

I have set DIFFUSE_ML_TO_INTERIOR = False for the time being in this test and Baltic now passes.

**Comment by marshallward** [comment]
My guess this is due to the many "left-right" calculations which appear in this function.

With the rotational invariance testing live, and the [apparently strong](https://codecov.io/gh/NOAA-GFDL/MOM6/src/dev%2Fgfdl/src/tracer/MOM_tracer_hor_diff.F90) (though not complete) coverage over this function, I am guessing that this does appear to be rotationally equivalent and can be closed.

If I'm wrong, then we should discover it as we complete coverage over the few remaining tests.
