### ISSUE TITLE
Vertical integral of vmo in rho2-space inconsistent with z-space

### ISSUE THREAD

**Issue by jkrasting** [NOAA-GFDL/MOM6#639]
Rong Zhang, @StephenGriffies are here with me.  We are looking at vmo in the rho2 space.

Rong plotted the vertical and zonal integration of vmo and found that the values are much bigger than in z-space

```
use ocean_annual_rho2.0001-0001.vmo.nc
use ocean_annual_z.0001-0001.vmo.nc
plot VMO[k=@sum,x=@sum,d=2]/1.e6/1035., VMO[k=@sum,x=@sum,d=1]/1.e6/1035.
```
![vmo](https://user-images.githubusercontent.com/6594675/32193354-5e1904fa-bd8d-11e7-9827-6ed19b19c2de.gif)

**Comment by MJHarrison-GFDL** [comment]
@adcroft and I saw this on Monday. Density space thicknesses are wrong as well.

**Comment by jkrasting** [comment]
Thanks Matt - This also means that the downstream refineDiag scripts that
use 'vmo' in density space are incorrect.

**Comment by adcroft** [comment]
I started looking into the vmo problem and while tracing it back found the bad values with Zhi, reported in #638. I'm hoping they are one and the same.

**Comment by adcroft** [comment]
Unfortunately my code that fixes #638 does not resolve this issue, #639 :(

**Comment by adcroft** [comment]
@MJHarrison-GFDL and I found the cause of this: the build_rho_column() function has only ever been coded to build coordinates with the same number of layers as the source grid. In OM4, we opted to reduce output volume by choosing only 35 isopycnal layers. The upshot is that the diagnostic rho coordinate ends up only seeing the first 35 layers of the 75 model-layers and thus is not full depth.

If I can't code up a fix by tomorrow lunch, I'll revert OM4 rho2 diagnostics to use the same densities as we use the hycom1 coordinate configuration of the model itself.

**Comment by ashao** [comment]
One other thing about the density output that I realized is that care needs
to be taken about which temperature and salinity should be used when the
diagnostic is posted. For example, for the umo and vmo diagnostics, the
layer thicknesses used are from before the dynamics routines, but the T/S
field used are the ones from the last time the diagnostic grids were
updated.

On Oct 31, 2017 5:33 PM, "Alistair Adcroft" <notifications@github.com>
wrote:

@MJHarrison-GFDL <https://github.com/mjharrison-gfdl> and I found the cause
of this: the build_rho_column() function has only ever been coded to build
coordinates with the same number of layers as the source grid. In OM4, we
opted to reduce output volume by choosing only 35 isopycnal layers. The
upshot is that the diagnostic rho coordinate ends up only seeing the first
35 layers of the 75 model-layers and thus is not full depth.

If I can't code up a fix by tomorrow lunch, I'll revert OM4 rho2
diagnostics to use the same densities as we use the hycom1 coordinate
configuration of the model itself.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NOAA-GFDL/MOM6/issues/639#issuecomment-340945818>, or mute
the thread
