### ISSUE TITLE
problem with diagnostics boundary_forcing_heat_tendency and salt analog

### ISSUE THREAD

**Issue by StephenGriffies** [NOAA-GFDL/MOM6#646]
The subroutine diagnose_boundary_forcing_tendency inside that module 

src/parameterizations/vertical/MOM_diabatic_driver.F90

is meant to diagnose all of the boundary fluxes (at least the surface boundary) of heat and salt.  Instead, it merely computes the time tendency of the tracer content.  It does not access any of the boundary flux arrays (e.g., shortwave, longwave, etc.).  So I am puzzled as to why this routine has the name "boundary_forcing".

I do not know if I wrote this routine: it looks like my style of naming.  But I am unsure.  @ashao has done some work on this routine, so may be able to shed light.  

I am led to look at this diagnostic since it appears there is a remaining problem with the 3d heat (and salt) budgets.  The errors are larges near the surface.  So the best guess is that the boundary forcing diagnostic is at fault.

**Comment by ashao** [comment]
I responded to the wrong Github notification, but I'll repeat the gist of it here.

I had been able to get the 3D salt budget to close with the remapped diagnostics, but have not checked the heat budget, which would suggest that the diagnostic remapping is not at fault. I'll take a look at this as well to see if I can make heads or tails of this. In the meantime, @StephenGriffies , is this problem isolated to the remapped diagnostics or the native-space diagnostics as well?

**Comment by ashao** [comment]
Also, the subroutine that applies boundary fluxes is applyBoundaryFluxesInOut found in src/parameterizations/vertical/MOM_diabatic_aux.F90. diagnose_boundary_forcing_tendency does what you describe and just calculates the change in tracer concentration or content from before and after applyBoundaryFluxesInOut.

**Comment by ashao** [comment]
With the output at /work/aes/OM4_025/frazil_diag, the largest difference between osalttend and (Sh_tendency_vert_remap + osaltdiff + S_advection_xy + boundary_forcing_salt_tendency) is ~10^-4. For the analogous heat terms (and adding on the frazil term), I'm getting a difference of about 10^3. 

@MJHarrison-GFDL I know you had tracked down the appropriate heat budget terms in native space at some point. Am I missing a term?

**Comment by StephenGriffies** [comment]
@ashao  I agree: The subroutine diagnose_boundary_forcing_tendency computes the tendency just due to boundary fluxes.  I believe I wrote that routine.  Now I recall what it does.  Thanks.  

@nikizadehgfdl saved native and remapped diagnostics for OM4_025 a few days ago (before the frazil fix) in this directory 

/work/Niki.Zadeh/OM4p25_baseline

The 3d native heat budget closes fine.  But the z-diagnostics fail.  The frazil term was implicated as part of the problem. But now with fix from @ashao the frazil is likely not the problem (at least now it is self-consistent thanks to @ashao).  

I am suspicious of the boundary fluxes on the z-grid.  There was some work done with this diagnostic earlier with thickness updates.  I believe the problem that motivated looking at that routine related to vertical sum inconsistencies. I do not recall investigating the full 3d budget.  So it is worth looking again to see that the thicknesses are properly updated for the boundary flux diagnostics.

Note that for the salt budget, any individual term is far smaller in magnitude than for the heat budget.  So ~10^-4 error in the salt budget is not small.

**Comment by ashao** [comment]
You are correct that the problem before was that the vertical sums were not matching. Also, the 10^-4 error is about 10% of the total salt tendency for that grid cell. The thicknesses seem like they are correct and the v_extensive flags are set correctly. I'll dive further down the rabbit hole and let you know what I come up with.

**Comment by StephenGriffies** [comment]
I am relatively confident the bug lives in the remapped boundary_forcing diagnostic. All tests work fine with the native layer output.  

Here is what I have done to support the boundary forcing hypothesis.  I examined output in the 2-day test from 

/work/aes/OM4_025/heat_salt_budget/19000101.ocean_annual_z.nc

--Depth integrated sanity checks are satisfied
  H_TENDENCY_VERT_REMAP[k=@sum] = 0 
  OPOTTEMPDIFF[k=@sum] = 0

--Depth integrated heat budget check is satisfied (thanks to the recent frazil fix from @ashao)
  shade/l=2 OPOTTEMPTEND[k=@sum] -  BOUNDARY_FORCING_HEAT_TENDENCY[k=@sum] -  FRAZIL_HEAT_TENDENCY[k=@sum] - T_ADVECTION_XY[k=@sum]  = geothermal heating

--vertical slice fails, with failure isolated to the upper ocean, hence my hypothesis that the problem sits with BOUNDARY_FORCING_HEAT_TENDENCY.  Here is a sample slice away from bottom (to avoid geothermal term) and in the upper ocean

shade/l=2/y=0/z=0:200/x=150e:150w  OPOTTEMPTEND - TH_TENDENCY_VERT_REMAP - T_ADVECTION_XY -BOUNDARY_FORCING_HEAT_TENDENCY - OPOTTEMPDIFF - FRAZIL_HEAT_TENDENCY

The same slice from z=200:1000 shows a satisfactory balance.  


Besides needing to be sure the grid thicknesses have been properly updated for the diagnostic post of BOUNDARY_FORCING_HEAT_TENDENCY, we need to be sure the "h_old" and "h" grid thicknesses are the correct thicknesses.  We are using them to diagnose the thickness weighted tendencies ala the following line for heat 

src/parameterizations/vertical/MOM_diabatic_driver.F90
 work_3d(i,j,k) = GV%H_to_kg_m2 * tv%C_p * Idt * (h(i,j,k) * tv%T(i,j,k) - h_old(i,j,k) * temp_old(i,j,k))

We do something similar in MOM.F90 for the total time step heat changes as per this code 
    do k=1,nz ; do j=js,je ; do i=is,ie
      work3d(i,j,k)     = (tv%T(i,j,k)*CS%h(i,j,k) - CS%Th_prev(i,j,k)) * Idt * GV%H_to_kg_m2 * tv%C_p
      CS%Th_prev(i,j,k) =  tv%T(i,j,k)*CS%h(i,j,k)
    enddo ; enddo ; enddo
    if (CS%id_Th_tendency    > 0) call post_data(CS%id_Th_tendency, work3d, diag)

**Comment by ashao** [comment]
Thanks for that level of detail and for doing some of those sanity checks. Because you previously stated that the heat budget on the native grid closes, I would assume that all the calculations are done correctly and that as you say, the problem lies somewhere in the remapping. I'll let you know what I come up with.

**Comment by ashao** [comment]
I've been looking at plots of the the cumulative depth integrals of each tendency term for columns that exhibited the worst errors in the remapped diagnostic. The only term which looks incredibly wrong is the total time tendency term opottemptend.

![image](https://user-images.githubusercontent.com/3845639/32569528-32c64afc-c476-11e7-8b3a-bab5c1930f39.png)

We didn't catch this before because the column integrals between both the native and remapped coordinates differ by only 6 or 7 decimal places.

By the way, I don't think the boundary_forcing tendency is the problem:

![image](https://user-images.githubusercontent.com/3845639/32569586-5f8f8012-c476-11e7-85b1-7ee814ff3476.png)

This may again come down to a layer thickness issue, but I'll have to check this out further.

**Comment by StephenGriffies** [comment]
Good thought.  I had presumed the total tendency was fine.  But it too may be off.  It's diagnosis involves multiplying by thicknesses, so there is a chance it if problematic.

**Comment by ashao** [comment]
I have some hints on things to try and/or think about harder tomorrow. The heat and salt fluxes due to the residual mean transport (and neutral diffusion) are posted in the subroutine post_TS_diagnostics which is called if advection/diffusion has occurred but after step_MOM_thermo has been called when DIABATIC_FIRST = False. These diagnostics should be posted right after their respective subroutines. 

Also, we could consider moving the remainder of the diagnostics in post_TS_diagnostics to the same level as post_surface_diagnostics and post_integrated_diagnostics. opottemptend and osalttend would then represent the tendencies over an entire call to step_MOM.

**Comment by StephenGriffies** [comment]
Good ideas.  

Note that I am away for some personal leave time until 14Nov.  Good luck with the searches...

**Comment by ashao** [comment]
This issue should be closed as it is superseded by #653

**Comment by StephenGriffies** [comment]
I agree.  This issue should be closed.
