### ISSUE TITLE
Error while Compiling the FMS shared code

### ISSUE THREAD

**Issue by TejuJ** [NOAA-GFDL/MOM6#647]
Trying to install MOM6 from this link 

[https://github.com/NOAA-GFDL/MOM6-examples/wiki/Getting-started#setting-up-the-compile-environment](url)
 for cray compilers but getting following error while compilation of FMS
module coupler_types_mod
       ^
ftn-855 crayftn: ERROR COUPLER_TYPES_MOD, File = ../../../../src/FMS/coupler/coupler_types.F90, Line = 1, Column = 8
  The compiler has detected errors in module "COUPLER_TYPES_MOD".  No module information file will be created for this module.

    call data_override(gridname, var%bc(n)%field(m)%name, var%bc(n)%field(m)%values, Time)
                                                                             ^
ftn-786 crayftn: ERROR CT_DATA_OVERRIDE_2D, File = ../../../../src/FMS/coupler/coupler_types.F90, Line = 3740, Column = 78
  An actual argument must be definable when associated with a dummy argument that has INTENT(OUT) or INTENT(INOUT).

    call data_override(gridname, var%bc(n)%field(m)%name, var%bc(n)%field(m)%values, Time)
                                                                             ^
ftn-786 crayftn: ERROR CT_DATA_OVERRIDE_3D, File = ../../../../src/FMS/coupler/coupler_types.F90, Line = 3754, Column = 78
  An actual argument must be definable when associated with a dummy argument that has INTENT(OUT) or INTENT(INOUT).

**Comment by adcroft** [comment]
We have a pull request in to FMS to fix this issue (NOAA-GFDL/FMS#43).

**Comment by TejuJ** [comment]
hello adcroft
   thank you for reply I fixed this issue but now getting following error


/dynamic -I../../../../src/MOM6/src/framework   ../../../../src/MOM6/src/core/MOM_forcing_type.F90

module MOM_forcing_type
       ^
ftn-855 crayftn: ERROR MOM_FORCING_TYPE, File = ../../../../src/MOM6/src/core/MOM_forcing_type.F90, Line = 2, Column = 8
  The compiler has detected errors in module "MOM_FORCING_TYPE".  No module information file will be created for this module.

!$OMP                     firstprivate(netT,netS)
                                            ^
ftn-676 crayftn: ERROR CALCULATEBUOYANCYFLUX2D, File = ../../../../src/MOM6/src/core/MOM_forcing_type.F90, Line = 920, Column = 45
  Variable "t$277" is specified in directive clause FIRSTPRIVATE and SHARED.

**Comment by adcroft** [comment]
Which version of the Cray compiler are you using? We haven't been using the
cray compiler ourselves (yet).

Also, did you enable openmp in the compiler options intentionally? We don't
normally use openmp (because not all parts of the model have fully debugged
OMP directives) so if you can avoid enabling openmp this should get you
past this particular problem. I'm not entirely sure what's wrong with that
directive so to figure it out we'll have to try cray+openmp ourselves.

I've checked that the model builds for me with CCE 8.5.0 without openmp.
This is new - until recently FMS didn't compile - so we'll now add cray to
our testing suite. I already know some experiments crash. :(

**Comment by TejuJ** [comment]
By default openmp option is enabled so I disabled openmp. Now its working fine. Thank you for help :)
