### ISSUE TITLE
G%dyCu =  G%dy_Cu in reset_face_length_list changes answers

### ISSUE THREAD

**Issue by wfcooke** [NOAA-GFDL/MOM6#685]
@adcroft @Hallberg-NOAA 
After modifying channels @MJHarrison-GFDL told me to check dxcv and dycu in ocean_static.nc/ocean_geometry.nc to see the effect of the narrowed channel. Those variables did not change when I correctly added a channel (areacello_Cu did change, so I know I was adding the channel correctly)

That is because 

https://github.com/NOAA-GFDL/MOM6/blob/85c2ea0bf81b12a316fe40bc7713520f14a558fb/src/initialization/MOM_shared_initialization.F90#L912

modifies dy_Cu not dyCu (similarly at line 930 for dx_Cv vs dxCv) 
dyCu and dxCv are output to ocean_geometry, not the modified variables.

dy_Cu is a masked version of dyCu so I thought perhaps I need to modify that variable too. 
So I added 
      G%dyCu(I,j) = G%dy_Cu(I,j)
directly after the above line. 

But this changes answers. 

Why is there a need for the masked and unmasked variable?
Have I discovered an issue where somebody coded G%dyCu instead of G%dy_Cu somewhere else in the code?

**Comment by adcroft** [comment]
dyCu is the nominal grid length and dy_Cu is the modulated (by channels)
length. They are kept separate and get used in different ways. It looks
like the diagnostic of dy_Cu is missing. I thought there used to be one but
don't see it now.

**Comment by Hallberg-NOAA** [comment]
The value of G%dy_Cu is available for output as the static diagnostic dyCuo, and similarly G%dx_Cv is available as the diagnostic dxCvo. Both are written by the subroutine write_static_fields(), and both appear the available_diags files for various test cases.

  The MOM6 code is working as intended, and all of the diagnostics that were discussed in this issue hare available, and have been since PR #696, which was added shortly after this issue was first opened.
