### ISSUE TITLE
Inconsistent short names in registry for temperature and salinity

### ISSUE THREAD

**Issue by ashao** [NOAA-GFDL/MOM6#699]
The short names used for temperature and salinity were changed from 'T' and 'S' to 'temp' and 'salt' in https://github.com/NOAA-GFDL/MOM6/commit/a87c5efb02ba6a484f8e5e9ec832e7117660f9df. Some parts of the code which loop over the tracer registry and have exceptions for these tracers (e.g. https://github.com/NOAA-GFDL/MOM6/blob/d2a70378f382db23e74732e51201ae3109cc8892/src/tracer/MOM_neutral_diffusion.F90#L511-L525) are not correctly processed. As far as I can see this affects the Th_tendency_vert_remap and opottemppmdiff diagnostics (and the salinity analogues). 

While the easy solution is to change the code so that the names are all consistent, I wanted to propose adding an 'integer' field to the Tracer type which could take the values of 1 for temperature, 2 for salinity, and 3 for passive tracers. This has the added benefit that checks like the one shown above will not be string comparisons  and makes it  easy to distinguish between the active and passive tracers in the tracer registry. 

If you agree with this proposal, let me know and I'll go ahead with a PR implementing this.

**Comment by StephenGriffies** [comment]
This sounds like a useful plan, so long as we can always depend on the mapping:

temp=1
saln=2
passive=3

I recall in MOM5 this mapping was not always the case, which was due to using Slater's tracer manager.  But if we are assigning the mapping in MOM6, and can rely on it, then I support the change.  

Others?

**Comment by Hallberg-NOAA** [comment]
@ashao, I do not care for the idea of having special magic numbers to differentiate T and S from other tracers.

  To handle the fact that T and S (and any other tracer, for that matter) may follow a different pattern in generating diagnostics, the tracer registry calls already permit additional information to be provided. To retain "T", for instance, use Tr%flux_nameroot instead of Tr%name. To know that there is a unit conversion in going from concentrations to fluxes, there are scaling factors and new units that can be provided.  In doing so, we avoid having a large volume of "special case" code. By contrast, having a "special case" number only encourages people to use shortcuts rather than figuring out what the general pattern should be.

  A quick grep reveals only 3 or 4 places in the MOM6 code (in MOM_ALE.F90 and MOM_neutral_diffusion.F90) where "special value" names are used in the logic, and in those
places the diagnostics for other tracers are actually inconsistent with units used elsewhere for these tracers.  These locations can be fixed by making proper use of information that is already present in the tracer registry.

**Comment by ashao** [comment]
After discussions with @adcroft and @Hallberg-NOAA, I agree with their recommendation against in differentiating between active and passive tracers in the registry. The argument that sold me was that the pointers to T and S in the thermodynamic type implicitly imply that these tracers are being used as active tracers. The tracer registry in contrast is then deliberately agnostic to passive vs. active distinctions.

To resolve the issue with the diagnostics, the special cases mentioned by @Hallberg-NOAA will be updated to the new names 'temp' and 'salt'. A PR is forthcoming to close this issue.

**Comment by ashao** [comment]
@Hallberg-NOAA: I was looking into how we can collapse some of the name-based checks for temperature and salinity. They all center around how to properly convert from concentrations to cell-integrated quantities for diagnostic purposes. Much of that code is now redundant due to the capabilities added to the tracer registry in PR #680 and can be replaced in a similar way that the advection diagnostics were. One additional field will need to be added to the tracer type to store the tracer concentration tendency, however this field can be constructed automatically since it's just a concatenation of the tracer concentration unit and 's-1'.

Unless there are any objections, I'll do this in lieu of doing the simple renaming fix for this issue.

**Comment by ashao** [comment]
Closed by #702
