### ISSUE TITLE
Initialize massless layers to 0 thickness so masked-PE results reproduce non-masked

### ISSUE THREAD

**Issue by adcroft** [NOAA-GFDL/MOM6#73]
To avoid divisions by zero, thicknesses default to ANGSTROM. ANGTROM=0 should work and doing so will allow us to test and validate solutions with and without mask_tables.
- Might need to add land masks to the APE calculation.

**Comment by Hallberg-NOAA** [comment]
We have been able to use ANGSTROM=0 for all of the test cases in MOM6-examples for over a year now, although this does require that the various ..._2018_ANSWERS run-time flags be set to .false. (which has been the default since PR #1127 was merged into dev/gfdl in June, 2020).  Both the change to ANGSTROM = 0 and changing the value of the various ..._2018_ANSWERS flags will change answers, although the solutions are all qualitatively similar.
