### ISSUE TITLE
Global indexing option should be deprecated 

### ISSUE THREAD

**Issue by MJHarrison-GFDL** [NOAA-GFDL/MOM6#747]
Parameter "GLOBAL_INDEXING" is a leftover flag from earlier development work and should be deprecated. It is not a desired option.

**Comment by Hallberg-NOAA** [comment]
Actually, I disagree about the undesirability of the GLOBAL_INDEXING option.

   This flag has been of great value in SIS2 in ensuring that we are handling our indexing appropriately, and it should become a more widely test of possible indexing errors in MOM6, as this flag should not change answers.  The bugs that this flag would reveal could in some cases also be related to halo sizes or the use of symmetric memory, both of which are tested. (However, I believe that there are issues that would need to be resolved in some portions of the MOM6 code before GLOBAL_INDEXING would in fact give the same answers, which is why this option is not being actively used in testing yet.)
