### ISSUE TITLE
Cleanup of diapycnal diffusivity specification

### ISSUE THREAD

**Issue by adcroft** [NOAA-GFDL/MOM6#75]
MOM_set_diffusivity() is a bit of a mess. Especially after @adcroft-gfdl added KPP to it.

**Comment by Hallberg-NOAA** [comment]
MOM_set_diffusivity has undergone dramatic revisions since this issue was first introduced, and is now much more sensibly organized than it was in 2014. If there are specific structural changes that should be considered for this code, please introduce them as new and more targeted issues, but this broad issue can be closed.
