### ISSUE TITLE
INPUT_STR_LENGTH is too short for many open boundary segment data specifications  

### ISSUE THREAD

**Issue by andrew-c-ross** [NOAA-GFDL/MOM6#75]
The maximum length of a line in an input parameter file is set in MOM_file_parser:
https://github.com/NOAA-GFDL/MOM6/blob/2e72b88647a2891ddadf43bf2c19596a356608ac/src/framework/MOM_file_parser.F90#L19

For regional models, it is very easy for the necessary OBC_SEGMENT_*_DATA specifications to exceed this length. We have been using cryptically short file names for the segment data to keep the overall length inside the limit. Furthermore, if the length is exceeded the returned error is usually a red herring ("There is a mismatched quote in the parameter file" because the line is not read to the end containing the closing quote). 

An easy solution is to increase INPUT_STR_LENGTH in MOM_file_parser. 

Is this fine, or is there a better solution? I've seen the discussion at [mom-ocean #1254](https://github.com/mom-ocean/MOM6/issues/1254), but I'm not sure if and how that could be implemented for this case.

Also, I thought this has been brought up before, but I was unable to find anything, so apologies if this is a duplicate.

May also be relevant to #74 .

**Comment by Hallberg-NOAA** [comment]
Simply increasing the INPUT_STR_LENGTH would be the simplest solution, but do we know how large it would need to be in all cases?  Moreover, there are enough of these lines on all PEs that hard-coding the string sizes to be very large could have significant memory implications, even in cases that do not need such long lines.

  We use an array of these input lines, which we use and broadcast all at once, so they all need to be of the same size.  As a second alternative, it might be possible to change the array of input lines into an array of allocatable strings (perhaps this would have to be in a new type), each with a different length, but I suspect that this would require either one global broadcast per line, or some clever packing and unpacking of a big buffer.

  As a third alternative, we could probably determine the length of the longest input line in each file at run-time, and use that instead of the hard-coded INPUT_STR_LENGTH parameter.  Would that suffice?

  The fourth alternative we could consider would be to add support for multi-line input strings, with a line continuation. However, this might require more extensive development and testing.
