### ISSUE TITLE
Divide by zero in post_surface_diagnostics()

### ISSUE THREAD

**Issue by adcroft** [NOAA-GFDL/MOM6#767]
At [L1189 in `post_surface_diagnostics()`](https://github.com/NOAA-GFDL/MOM6/blob/05b41be49d0b7fbdac8443769804286548fdc51b/src/diagnostics/MOM_diagnostics.F90#L1189) there is a division by zero which has been passed as an argument, `dt_int`. The argument is apparently the accumulated time used by thermodynamics, `CS%time_in_thermo_cycle`, passed at [L812 of `step_MOM()`](https://github.com/NOAA-GFDL/MOM6/blob/05b41be49d0b7fbdac8443769804286548fdc51b/src/core/MOM.F90#L812-L813).

- `CS%time_in_thermo_cycle` is properly initialized to zero at [L2029](https://github.com/NOAA-GFDL/MOM6/blob/05b41be49d0b7fbdac8443769804286548fdc51b/src/core/MOM.F90#L2029) during the `_init` phase.
- `CS%time_in_thermo_cycle` maybe reset to zero at [L512](https://github.com/NOAA-GFDL/MOM6/blob/05b41be49d0b7fbdac8443769804286548fdc51b/src/core/MOM.F90#L524).
- `CS%time_in_thermo_cycle` is possibly incremented by `dtdia` at [L622](https://github.com/NOAA-GFDL/MOM6/blob/05b41be49d0b7fbdac8443769804286548fdc51b/src/core/MOM.F90#L622).
- `CS%time_in_thermo_cycle` is also possibly incremented by `dtdia` at [L716](https://github.com/NOAA-GFDL/MOM6/blob/05b41be49d0b7fbdac8443769804286548fdc51b/src/core/MOM.F90#L716).
- The post (and division by zero happens at [L812](https://github.com/NOAA-GFDL/MOM6/blob/05b41be49d0b7fbdac8443769804286548fdc51b/src/core/MOM.F90#L812-L813) when `cycle_end=.true.`.

I am unsure what exactly is meant to be happening here. ☹️  However, I would have thought the reset should happen conditionally immediately after the post. Further, the post would ideally have a `if (do_thermo)` around it but cannot because the post is for both thermodynamic and non-thermodynamic quantities. I therefore guess the simplest solution is to only do the [four individual posts](https://github.com/NOAA-GFDL/MOM6/blob/05b41be49d0b7fbdac8443769804286548fdc51b/src/diagnostics/MOM_diagnostics.F90#L1223-L1253) within `post_surface_diagnostics()` within a `if (dt_int>0)`. However, _I am unsure_.

Detected at NCI for OM4_025 test, thanks @nicjhan :
https://accessdev.nci.org.au/jenkins/job/mom-ocean.org/job/MOM6_run/build=DEBUG,compiler=intel,experiment=ice_ocean_SIS2-OM4_025,label=nah599,memory_type=dynamic/lastBuild/console

**Comment by Hallberg-NOAA** [comment]
These diagnostics are valid for a time interval that is set at https://github.com/NOAA-GFDL/MOM6/blob/05b41be49d0b7fbdac8443769804286548fdc51b/src/core/MOM.F90#L811 to be of duration CS%time_in_thermo_cycle. When taking time-averages, the values in the numerator and denominator cancel. In the specific case where the valid time interval is 0, the underlying call to the FMS send_data routine is given a weight of 0. Because 0*NaN = NaN, this is still a problem, but it is clear that _none_ of the diagnostics in this routine should be called when the time interval is 0.

  The specific problematic instance here arises when the thermodynamics span the forcing cycle, post_surface_diagnostics is being triggered even though no thermodynamics have occurred. The other thing that makes this code complicated is that the OS%frazil field is not primarily a diagnostic; rather it is the accumulated heat demand due to the frazil and it must be passed up to the sea-ice, so zeroing it out right after the post would be a very bad idea. Similarly, the other net-heat input terms (like tv%TempxPmE) are used later in accumulate_net_input to monitor the model's heat budget and make sure that it is closed to something like roundoff.

  The correct solutions here are any combination of:
  1) Do not send _any_ of the diagnostics inside post_surface_diagnostics() when  dt_int is 0;
  2) Do not call post_surface_diagnostics() at all when CS%time_in_thermo_cycle = 0;
and
  3) If enable_averaging() is called with a time interval of 0, perhaps this should be the same as calling disable_averaging().

  Thank you, @nicjhan and @adcroft , for detecting this problem.  I will put in PR with the first two changes later today, and we can discuss whether the 3rd is also a good idea or whether it might have unintended consequences.
