### ISSUE TITLE
Grid of MOM6

### ISSUE THREAD

**Issue by agustinhofbn** [NOAA-GFDL/MOM6#878]
Dear,

I'm trying to make a new grid using MOM6. In MOM5_SIS generated the ocean grid file, so how do I generate the same file in MOM6 and run the model with this new grid?

Thanks in advance,

**Comment by adcroft** [comment]
The tools for generating the exchange grid and underlying model grids are at https://github.com/NOAA-GFDL/FRE-NCtools. I'm surprised you think MOM5_SIS generated a grid; FMS coupled models always use grids read from file. These are generated during preprocessing in order to calculate an exchange grid which is needed for coupling. Instructions for compiling an ice-ocean MOM6-SIS2 model are at https://github.com/NOAA-GFDL/MOM6-examples/wiki/Getting-started#compiling-mom6-in-mom6-sis2-coupled-mode. This executable will work with examples under ice_ocean_SIS2 of MOM6-examples.

**Comment by agustinhofbn** [comment]
Thank you very much,

I will proceed in this manner.
