### ISSUE TITLE
Extra water depth added when remapped to z-coordinate

### ISSUE THREAD

**Issue by hlkong** [NOAA-GFDL/MOM6#889]
I was trying to output diagnoses in both density and z coordinates (the model ran in density coordinate) and the designed topography has a maximum depth of 4km. Yet in the z-coordinate output the quantity z_i (interface height) can be as deep as 4.25km while the deepest z_l (cell center depth) is 4km. I'm confused and am wondering if anyone knows why it is designed in this way? Would this imply that the remapped z-coordinate quantities should be dealt with differently? (and how?)

------------------

An extra question: what is the diagnosis vh_rho from the module of ocean_module_z? Presumably it is the meridional volume transport (m^3/s) in z coordinate within each grid cell but I've found it's substantially different from v.*h.*dx, where v & h are z-coordinate diagnoses and dx is just longitudinal increment of cell width. But what else can vh\_rho be? 

Thanks!

**Comment by ashao** [comment]
Are you specifying the target diagnostic z coordinate in MOM_input? If not
and you're getting remapped diagnostic by using ocean_model_z in
diag_table, I believe it defaults to the levels used in the World Ocean
Atlas.

**Comment by hlkong** [comment]
Thanks @ashao ! No I didn't specify that and yes I am using ocean_model_z. But still it's weird the deepest level can go below topography... re-mapped interface height (e_z) seems fine, though

**Comment by Hallberg-NOAA** [comment]
This is a diagnostic issue that does not impact any output on the model's native grid or the solutions themselves.

  When writing to a z-file, properly averaged values are reported for any cells with water in depth range spanned by the target (1-dimensional) z-grid.  This is the result of the choice to use a finite volume formulation for these averages, rather than reporting the values interpolated to specific depths. Given that there is a choice here between reporting valid values that make sense if treated properly (by use of e_z), or not reporting these values at all, I think that reporting them is the right decision.

  One optional enhancement might be to adjust the depth ranges reported in the Z-coordinate axis in the file so the bottom depth does not exceed the deepest depth in a particular configuration, but this would probably only be of substantial help in idealized configurations with a well-defined and widely used maximum ocean depth, and even then care would have to be taken in places where the depth is shallower.

  I think that this has been a useful discussion, but that this issue can now be closed without triggering specific changes to the MOM6 code.
