### ISSUE TITLE
openmp issue with symmetric memory 

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/MOM6#895]
In current dev/gfdl (02/13/2019) the OMIP SPEAR test case crashes with extreme values if ocean-ice is compiled with -openmp (even for 1 thread). 
This does not happen for non-symmetric build models (SPEAR has to use symmetric memory).
This does not happen with non-openmp symmetric build.

So, most probably some var in symmetric code path has a openmp shared vs (first)private declaration issue.

```
WARNING from PE   116: Extreme surface sfc_state detected: i=   9 j=   5 x=-200.738 y=  77.217 D= 8.0150E+01 SSH=-3.1768E+02 SST=-1.7747E+00 SSS= 2.8840E+01 U-= 8.7743E+00 U+= 8.7816E+00 V-=-1.1645E+01 V+= 1.1746E+01
fms_MOM6_SIS2_com  0000000001328026  mpp_mod_mp_mpp_er          69  mpp_util_mpi.inc
fms_MOM6_SIS2_com  00000000007EC437  mom_mp_extract_su        3023  MOM.F90
fms_MOM6_SIS2_com  00000000007DA0C2  mom_mp_step_mom_          842  MOM.F90
fms_MOM6_SIS2_com  000000000074665E  ocean_model_mod_m         578  ocean_model_MOM.F90
fms_MOM6_SIS2_com  000000000040B8D6  MAIN__                   1082  coupler_main.F90
```

**Comment by Hallberg-NOAA** [comment]
Please try using the DEBUG=True flag in a pair of short runs of your configuration in which MOM6 is compiled with and without -openmp to see where in the code the answers change. You will want to compare the output from MOM6 to stdout (usually directed to two files because there is a lot of output).  In a case like this where two modes are supposed to give identical answers, we have found this to be the most expeditious approach for tracking down the problem.

**Comment by nikizadehgfdl** [comment]
I tried OM_1deg experiment in symmetric mode with openmp (with and without VERTEX_SHEAR). This issue is not reproducible with the current dev/gfdl branch. It's probably been fixed. Closing.
