### ISSUE TITLE
Reference density RHO_0 should be tightly connected to prescribed layer densities

### ISSUE THREAD

**Issue by navidcy** [NOAA-GFDL/MOM6#904]
When working in isopycnal mode in which I prescribe the layer densities `ρ_1`, `ρ_2`, ... , `ρ_n`, layer rest heights `H_1`, `H_2`,... `H_n`, and also the wind stress `τ_x` the model does not include the wind stress forcing in layer 1 as
```
τ_x/ρ_1
```
but rather it does
```
τ_x/RHO_0
```
where `RHO_0` the reference density given in `MOM_input` file.

Two remarks:
1) Why not `τ_x/ρ_1`?

More importantly,
2) I find it very cumbersome that while I prescribe layer densities the model does not  use those to infer a reference density but rather it uses a completely independent parameter value `RHO_0` (which may have no relation to the prescribed layer densities in any way).

I suggest that, at least in isopycnal mode with prescribed layer densities/rest heights, the model should use the mean density
```
\sum_{j=1}^n ρ_j*H_j / \sum_{j=1}^n H_j 
```
as its reference density and **not** `RHO_0` as is currently implemented.

@adcroft and @Hallberg-NOAA, do you have any remarks on why the `RHO_0` density is used as described above?

**Comment by Hallberg-NOAA** [comment]
Thanks for asking, @navidcy. The answer here depends upon whether you are using the Boussinesq approximation.

  With the Boussinesq approximation, densities are replaced by a reference value, `RHO_0`, except where you are taking gradients or differences. In this case a stress between layers leads to equal and opposite accelerations for layers of the same thickness.

  When the Boussinesq approximation is not made, the value of RHO_0 should not change solutions in the dynamic core, and layer thicknesses have units proportional to kg m-2. If you look a bit more carefully at the code that applies the wind stresses in MOM_vertvisc.F90, the non-Boussinesq version does use RHO_0 when translating stresses into accelerations (even though the variable names make it look like they do by following older, Boussinesq naming conventions).

 Not making the Boussinesq approximation does lead to some complications in some of the process parameterizations in MOM6. For example, input vertical viscosities are still being specified in units of m2 s-1, not kg2 m-4 s-1, so that input values are consistent across modes and to comply with traditional practice. In these cases RHO_0 is used to make the unit conversion for specified vertical viscosities and diffusivities.  The uncertainties this introduces are typically less than of order 4%, (2% differences in density with the conversion factor squared), but given the large uncertainties in the values of these turbulent viscosities and diffusivities (and their spatial and temporary variations), and the fact that we do not include the temperature dependence in the background molecular values, this particular issue is not the thing that keeps me up at night.

  I hope that this helps.

**Comment by adcroft** [comment]
1. The rho_0 is a constant parameter in the Boussinesq Primitive Equations. The layer densities are variable. In the Boussinesq equations, all terms use rho_0 except the gravitational acceleration. Thus, the stress term uses rho_0.
2. In the Boussinesq equations, rho_0 is a representative density about which an expansion is made. It is not necessarily a volume mean although it is can be interpreted that way. Depending on the kind of mean, and reference pressure, you use that mean density can take on a wide range of useful values, e.g. the mean *surface* value is appropriate if you want to impart the same amount of momentum via winds in experiments with different stratification. Isopycnal models use a potential density and often use a reference pressure of 2000 dbar to capture the North Atlantic density structure. The mean sigma_2 is quite different from the actual mean in-situ density. In short, there is no clear definition of rho_0. Rho_0 is an external parameter like "g" and it is left to the user to set it. If you want to set rho_0 to the actual volume mean as you suggest then there is a technical hurdle to doing so in the code; the constants such as "G" and "RHO0" are read multiple times and are needed before the hydrography and initial conditions are set up. The easiest way to make you rho_0 the volume mean would be run the model in order to generate the initial condition file, calculate the mean density offline based on the hydrography, then set RHO0 as needed. I think you'll be better off choosing a convenient round number for rho_0 for all your experiments.

**Comment by navidcy** [comment]
@Hallberg-NOAA and @adcroft thanks for the clarifications. I'm closing the issue.
