### ISSUE TITLE
Output md5 checksum of input files to enhance reproducibility.

### ISSUE THREAD

**Issue by jbusecke** [NOAA-GFDL/MOM6#954]
I am currently trying to mirror the setup for the 1/8th deg `OM4p125_IAF_csf_JRA55do1-3_r5` from GFDL to the NASA discover cluster.

During the process I am always worried if I copy the correct files and I am looking for a way to check this.

Does MOM6 currently have the capability to write out md5 checksums of all the files used?

I think for reproducibility purposes it would be great to have an option to put out a file, e.g. `input_md5.txt` which contains:
```
INPUT/ocean_hgrid.nc       %%%%%%%%md5%%%%%%%%%
INPUT/geothermal.nc         %%%%%%%%md5%%%%%%%%%
....
```
This way I could make sure these files on the new cluster are exactly the same as on another cluster. 

Is something like this already done/possible?

**Comment by adcroft** [comment]
There are several separable issues here:
1. What is the origin of the input files? Are these the ones I should be using?
2. Did my transfer of files keep things intact?
3. Did the model read the files correctly?

For the OM4 grids, md5 checksums are available, e.g. [md5sums.txt](https://github.com/adcroft/OM4_025_grid/blob/master/md5sums.txt). This addresses both issues 1 and 2 but only for the OM4 configurations. Unfortunately the 1/8th config hasn't been elevated to the status of being version controlled and documented in the main repo - I don't know if md5 sums, or documentation, even exist for this config - you'll have to ask whoever built the grids. For now, the best you can do is generate your own with the first version you have and propagate them around.

For issue 3, we could conceivably have MOM6 report bitcounts (MOM6's checkum approach - see debugging below) for static inputs and even check against a file. This can safeguard against a glitch in the reading of data which has happened a few times on various of our HPCs. I don't think it would be easy to use md5 in place of MOM6 bitcounts but regardless this would cover issues 1 and 3. FMS has checksums recorded it's own output (e.g for reading/writing restart files) but since many input files are user generated or are original downloaded data this feature doesn't help here.

As an interim extreme resort, the flag DEBUG=True will dump checksums (not md5 though) of everything including the grid to the tty. We call it DEBUG because you would normally only use this in debug mode. If you have those checksums in hand (e.g. generate them in a trusted place) and you expect to have bitwise identical results between the two platforms then this is a powerful way to isolate where a divergence comes from. You can use this to cover the main issues even though it wasn't designed for this.

**Comment by jbusecke** [comment]
Thanks for the quick and detailed answer. I have confirmed the origin of the grid files with @nikizadehgfdl (taking care of 1 until a new grid version is released).
I generated md5 checksums [for the grid](https://github.com/jbusecke/model_setups) and for the preprocessed forcing files from [JRA55 v1.3](https://github.com/jbusecke/model_forcing). I will use those to check the file after the transfer to NASAs discover and Princetons Tiger (taking care of 2).
I will also try to look more into 3) and see how I can integrate this into our workflow. 

This was very helpful. Cheers
